# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Blog"
  pageRef = "blogs"
  weight = 10

[[main]]
  name = "Tips & Tricks"
  pageRef = "tips-tricks"
  weight = 20

[[main]]
  name = "Contribution"
  pageRef = "contributions"
  weight = 30

[[main]]
  name = "Events"
  pageRef = "events"
  weight = 40

[[main]]
  name = "About"
  pageRef = "about"
  weight = 50

[[main]]
  name = "Links"
  pageRef = "links"
  weight = 60

[[main]]
  parent = "Links"
  name = "Sovereign Cloud Community - NL"
  url = "https://sovereign-cloud.nl"

[[main]]
  parent = "Links"
  name = "Microsoft Community Hub"
  url = "https://techcommunity.microsoft.com/"

[[main]]
  parent = "Links"
  name = "Microsoft Learn"
  url = "https://learn.microsoft.com/"

[[main]]
  parent = "Links"
  name = "Azure Well-Architected Framework"
  url = "https://learn.microsoft.com/en-us/azure/well-architected/"

[[main]]
  parent = "Links"
  name = "Reliability Engineering | DevOps Leadership | Coaching"
  url = "https://qensus.com"

[[main]]
  parent = "Links"
  name = "Observability Experts | Training"
  url = "https://www.observion.nl/"

[[main]]
  parent = "Links"
  name = "LinkedIn"
  url = "https://www.linkedin.com/company/sovereign-cloud-nl-community"
#[[main]]
#  name = "Merch"
#  url = "https://www.teepublic.com/user/blowfish-store/t-shirts"
#  weight = 100

#[[main]]
#  name = "Test"
#  pageRef = "pagTest"
#  weight = 1000

[[main]]
  identifier = "twitter"
  pre = "x-twitter"
  url = "https://twitter.com/azurebuddy"
  weight = 200

#[[main]]
#  identifier = "mastodon"
#  pre = "mastodon"
#  weight = 300
#  url = "https://masto.ai/@AzureBuddy"

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/azure-buddy"
  weight = 400


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

 [[footer]]
   name = "Categories"
   pageRef = "tags"
   weight = 10

 [[footer]]
   name = "Authors"
   pageRef = "authors"
   weight = 20
